### ISSUE TITLE
Is there a plan for add mini GUI to mesalock-linux ?

### ISSUE THREAD

**Issue by cloudtrends** [mesalock-linux/mesalock-distro#6]
hi,

Is there a plan for add mini GUI to mesalock-linux ?

For some reason , or demo purpose for people who first time touch mesalock-linux , a GUI interface will be more acceptable for them .

Do we have a road map ?

thanks.

**Comment by mssun** [comment]
GUI is not on the plan right now. Since GUI on Linux has a **huge** C/C++ stack, making them memory safe is a big project. We are focusing on docker image, (high-end) IoT system in the short term. When all building blocks for GUI are ready, we can push forward to the GUI thing.

For demonstration purpose, we have a web service written in Rust right now. Later, we may consider adding more samples in various scenarios for demonstration. If you have any ideas on the demo, feel free to propose here. Thanks.

**Comment by mssun** [comment]
Another direction on these non-memory-safe packages is that we can **constrain the processes's capabilities** (e.g., using AppArmor). Therefore, although there are attack surfaces of the non-memory-safe processes, we can minimize the the consequences. Of course, all efforts here aim to achieve the rules-of-thumb for hybrid memory-safe architecture mentioned in the README.

For the GUI thing, firstly, we need to evaluation how large the non-memory-safe code base will be involved and how to constraint these code.

**Comment by cloudtrends** [comment]
Great explanation!
